"""Render a medical record as a doctor-ready PDF."""
from __future__ import annotations

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

PRIMARY = colors.HexColor("#27777F")
MUTED = colors.HexColor("#6B7280")
LIGHT_BG = colors.HexColor("#F3F4F6")

DISCLAIMER = (
    "This report is generated by ALRI, an AI-powered educational tool. "
    "It is not a medical diagnosis. Please consult a qualified healthcare "
    "professional before making any medical decisions based on this data."
)


def _status_colour(status: str | None) -> colors.Color:
    if not status:
        return MUTED
    s = status.lower()
    if s == "normal":
        return colors.HexColor("#12B76A")
    if s in {"high", "above", "borderline_high"}:
        return colors.HexColor("#F79009")
    if s in {"low", "below", "borderline_low"}:
        return colors.HexColor("#F04438")
    if s == "critical":
        return colors.HexColor("#D92D20")
    return MUTED


def _fmt_date(iso: str | None) -> str:
    if not iso:
        return "—"
    try:
        return datetime.fromisoformat(iso.replace("Z", "+00:00")).strftime("%d %b %Y")
    except ValueError:
        return iso[:10]


def render_medical_record_pdf(record: dict) -> bytes:
    """Takes the dict from build_medical_record() and returns PDF bytes."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=0.6 * inch,
        rightMargin=0.6 * inch,
        topMargin=0.5 * inch,
        bottomMargin=0.5 * inch,
        title="ALRI Medical Record",
    )

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], textColor=PRIMARY, fontSize=20, spaceAfter=4)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], textColor=PRIMARY, fontSize=13, spaceBefore=14, spaceAfter=6)
    body = ParagraphStyle("body", parent=styles["BodyText"], fontSize=10, leading=14)
    small = ParagraphStyle("small", parent=body, fontSize=8.5, textColor=MUTED)

    story: list = []
    profile = record.get("profile") or {}
    counts = record.get("counts") or {}

    # Header
    name = profile.get("name") or "Alri User"
    story.append(Paragraph("ALRI Medical Record", h1))
    story.append(Paragraph(f"For <b>{name}</b>", body))
    story.append(
        Paragraph(
            f"Generated {_fmt_date(record.get('generated_at'))} "
            f"&middot; {counts.get('scans', 0)} scans "
            f"&middot; {counts.get('skin_analyses', 0)} skin analyses "
            f"&middot; {counts.get('tracked_markers', 0)} tracked markers",
            small,
        )
    )
    story.append(Spacer(1, 8))

    # Profile block
    profile_rows = [["Email", profile.get("email") or "—"]]
    for label, key in [
        ("Age", "age"),
        ("Sex", "sex"),
        ("Weight (kg)", "weight_kg"),
        ("Height (cm)", "height_cm"),
    ]:
        val = profile.get(key)
        profile_rows.append([label, str(val) if val not in (None, "") else "—"])
    t = Table(profile_rows, colWidths=[1.4 * inch, 5.5 * inch])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), LIGHT_BG),
                ("TEXTCOLOR", (0, 0), (0, -1), MUTED),
                ("FONTSIZE", (0, 0), (-1, -1), 9.5),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LINEABOVE", (0, 0), (-1, 0), 0.5, colors.HexColor("#E5E7EB")),
                ("LINEBELOW", (0, -1), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
            ]
        )
    )
    story.append(t)

    # Trends section
    trends = record.get("trends") or []
    if trends:
        story.append(Paragraph("Biomarker trends", h2))
        trend_header = [["Marker", "Latest", "Unit", "Status", "Points"]]
        for tr in trends[:20]:
            pts = tr.get("points") or []
            latest = pts[-1] if pts else {}
            trend_header.append(
                [
                    tr.get("name") or "—",
                    f"{latest.get('value'):.2f}" if latest.get("value") is not None else "—",
                    latest.get("unit") or "—",
                    (latest.get("status") or "").replace("_", " ").title(),
                    str(len(pts)),
                ]
            )
        tt = Table(trend_header, colWidths=[2.4 * inch, 1.0 * inch, 0.9 * inch, 1.4 * inch, 0.9 * inch])
        tt.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTSIZE", (0, 0), (-1, 0), 9.5),
                    ("FONTSIZE", (0, 1), (-1, -1), 9),
                    ("ALIGN", (1, 1), (-1, -1), "LEFT"),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [colors.white, LIGHT_BG],
                    ),
                ]
            )
        )
        story.append(tt)

    # Scans
    scans = record.get("scans") or []
    if scans:
        story.append(PageBreak())
        story.append(Paragraph("Scans", h2))
        for s in scans[:30]:
            story.append(
                Paragraph(
                    f"<b>{_fmt_date(s.get('date'))}</b> "
                    f"&middot; {s.get('marker_count', 0)} markers "
                    f"&middot; {s.get('input_type') or 'upload'}"
                    + (" &middot; <i>locked</i>" if not s.get("full_unlocked") else ""),
                    body,
                )
            )
            summary = s.get("summary")
            if summary:
                story.append(Paragraph(summary, small))
            markers = s.get("markers") or []
            if markers:
                rows = [["Name", "Value", "Unit", "Range", "Status"]]
                for m in markers[:40]:
                    rng = "—"
                    lo, hi = m.get("reference_low"), m.get("reference_high")
                    if lo is not None and hi is not None:
                        rng = f"{lo}–{hi}"
                    rows.append(
                        [
                            m.get("name") or "—",
                            f"{m.get('value'):.2f}" if m.get("value") is not None else "—",
                            m.get("unit") or "—",
                            rng,
                            (m.get("status") or "").replace("_", " ").title(),
                        ]
                    )
                mt = Table(
                    rows,
                    colWidths=[2.2 * inch, 1.0 * inch, 0.8 * inch, 1.3 * inch, 1.3 * inch],
                )
                mt.setStyle(
                    TableStyle(
                        [
                            ("BACKGROUND", (0, 0), (-1, 0), LIGHT_BG),
                            ("TEXTCOLOR", (0, 0), (-1, 0), MUTED),
                            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                            ("TOPPADDING", (0, 0), (-1, -1), 3),
                            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                        ]
                    )
                )
                story.append(Spacer(1, 3))
                story.append(mt)
            story.append(Spacer(1, 10))

    # Skin analyses
    skin = record.get("skin_analyses") or []
    if skin:
        story.append(PageBreak())
        story.append(Paragraph("Skin analyses", h2))
        for sa in skin[:20]:
            story.append(
                Paragraph(f"<b>{_fmt_date(sa.get('date'))}</b>", body)
            )
            result = sa.get("result") or {}
            condition = result.get("condition") or result.get("primary_condition")
            severity = result.get("severity")
            summary = result.get("summary") or result.get("description")
            if condition or severity:
                story.append(
                    Paragraph(
                        f"{condition or ''}{' &middot; ' if condition and severity else ''}{severity or ''}",
                        small,
                    )
                )
            if summary:
                story.append(Paragraph(summary, small))
            story.append(Spacer(1, 8))

    # Disclaimer footer
    story.append(Spacer(1, 24))
    story.append(Paragraph(DISCLAIMER, small))

    doc.build(story)
    pdf = buf.getvalue()
    buf.close()
    return pdf
