from __future__ import annotations

import io
import os
import uuid
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

from app.config import settings


MEDICAL_DISCLAIMER = (
    "This report is generated by an AI system for informational purposes only and is not medical advice. "
    "It does not diagnose conditions. Please consult a qualified healthcare professional for medical guidance."
)


class ReportGenerator:
    """Generate a simple PDF report for a scan.

    Keeps dependencies minimal (reportlab only) and produces a readable, branded report.
    """

    def generate_pdf(
        self,
        *,
        scan_id: uuid.UUID,
        markers: list[dict],
        summary: str | None,
        correlations: list[dict] | None,
        user_profile: dict | None = None,
        user_name: str | None = None,
    ) -> bytes:
        buf = io.BytesIO()
        c = canvas.Canvas(buf, pagesize=letter)
        width, height = letter

        y = height - 0.75 * inch
        c.setFont("Helvetica-Bold", 16)
        c.drawString(0.75 * inch, y, "ALRI — Lab Result Interpretation")

        y -= 0.35 * inch
        c.setFont("Helvetica", 10)
        if user_name:
            c.drawString(0.75 * inch, y, f"Patient: {user_name}")
            y -= 0.2 * inch
        c.drawString(0.75 * inch, y, f"Scan ID: {scan_id}")
        y -= 0.2 * inch
        c.drawString(0.75 * inch, y, f"Generated: {datetime.utcnow().isoformat()}Z")

        if user_profile:
            y -= 0.2 * inch
            prof = ", ".join([f"{k}={v}" for k, v in user_profile.items() if v is not None])
            c.drawString(0.75 * inch, y, f"Profile: {prof}")

        y -= 0.35 * inch
        c.setFont("Helvetica-Bold", 12)
        c.drawString(0.75 * inch, y, "Summary")

        y -= 0.2 * inch
        c.setFont("Helvetica", 10)
        for line in _wrap_text(summary or "(No summary available)", max_chars=95):
            c.drawString(0.75 * inch, y, line)
            y -= 0.16 * inch

        y -= 0.25 * inch
        c.setFont("Helvetica-Bold", 12)
        c.drawString(0.75 * inch, y, "Markers")
        y -= 0.2 * inch

        c.setFont("Helvetica", 9)
        for m in markers:
            line = f"{m.get('name')}: {m.get('value')} {m.get('unit') or ''} | status={m.get('status')} | ref={m.get('reference_range') or ''}"
            for l in _wrap_text(line, max_chars=110):
                if y < 1.3 * inch:
                    c.showPage()
                    y = height - 0.75 * inch
                    c.setFont("Helvetica", 9)
                c.drawString(0.75 * inch, y, l)
                y -= 0.14 * inch

        if correlations:
            y -= 0.25 * inch
            if y < 1.3 * inch:
                c.showPage()
                y = height - 0.75 * inch
            c.setFont("Helvetica-Bold", 12)
            c.drawString(0.75 * inch, y, "Correlations")
            y -= 0.2 * inch
            c.setFont("Helvetica", 10)
            for corr in correlations:
                finding = corr.get("finding") or ""
                for l in _wrap_text(finding, max_chars=95):
                    if y < 1.3 * inch:
                        c.showPage()
                        y = height - 0.75 * inch
                        c.setFont("Helvetica", 10)
                    c.drawString(0.75 * inch, y, f"- {l}" if l == finding[: len(l)] else f"  {l}")
                    y -= 0.16 * inch

        # Disclaimer
        if y < 1.3 * inch:
            c.showPage()
            y = height - 0.75 * inch
        y -= 0.3 * inch
        c.setFont("Helvetica-Oblique", 8)
        for line in _wrap_text(MEDICAL_DISCLAIMER, max_chars=120):
            c.drawString(0.75 * inch, y, line)
            y -= 0.12 * inch

        c.showPage()
        c.save()
        buf.seek(0)
        return buf.read()

    def save_pdf(self, *, scan_id: uuid.UUID, pdf_bytes: bytes) -> str:
        # Local storage only (spec allows local volume or S3; S3 handled elsewhere)
        base = settings.STORAGE_PATH
        os.makedirs(base, exist_ok=True)
        fname = f"scan-{scan_id}.pdf"
        path = os.path.join(base, fname)
        with open(path, "wb") as f:
            f.write(pdf_bytes)
        return path


def _wrap_text(text: str, *, max_chars: int) -> list[str]:
    words = (text or "").split()
    lines: list[str] = []
    cur: list[str] = []
    cur_len = 0
    for w in words:
        add = len(w) + (1 if cur else 0)
        if cur_len + add > max_chars:
            lines.append(" ".join(cur))
            cur = [w]
            cur_len = len(w)
        else:
            cur.append(w)
            cur_len += add
    if cur:
        lines.append(" ".join(cur))
    return lines or [""]
