"""Generate a PDF report for a skin condition assessment."""
from __future__ import annotations

import io
import uuid
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas


MEDICAL_DISCLAIMER = (
    "This report is generated by an AI system for informational purposes only and is not medical advice. "
    "It does not diagnose conditions. Please consult a qualified dermatologist or healthcare professional "
    "for medical guidance."
)


class SkinReportGenerator:
    """Generate a simple PDF report from a skin analysis result."""

    def generate_pdf(
        self,
        *,
        analysis_id: uuid.UUID,
        analysis_result: dict,
        created_at: datetime | None = None,
        user_name: str | None = None,
    ) -> bytes:
        buf = io.BytesIO()
        c = canvas.Canvas(buf, pagesize=letter)
        width, height = letter

        y = height - 0.75 * inch
        c.setFont("Helvetica-Bold", 16)
        c.drawString(0.75 * inch, y, "ALRI — Skin Condition Assessment")

        y -= 0.35 * inch
        c.setFont("Helvetica", 10)
        if user_name:
            c.drawString(0.75 * inch, y, f"Patient: {user_name}")
            y -= 0.2 * inch
        c.drawString(0.75 * inch, y, f"Analysis ID: {analysis_id}")
        y -= 0.2 * inch
        ts = created_at.isoformat() if created_at else datetime.utcnow().isoformat()
        c.drawString(0.75 * inch, y, f"Date: {ts}")

        # Severity
        severity = analysis_result.get("severity", "unknown")
        y -= 0.4 * inch
        c.setFont("Helvetica-Bold", 12)
        c.drawString(0.75 * inch, y, f"Overall Severity: {severity.title()}")

        # Conditions
        conditions = analysis_result.get("conditions") or []
        if conditions:
            y -= 0.35 * inch
            c.setFont("Helvetica-Bold", 12)
            c.drawString(0.75 * inch, y, "Possible Conditions")
            y -= 0.25 * inch

            c.setFont("Helvetica", 10)
            for cond in conditions:
                name = cond.get("name", "Unknown")
                confidence = cond.get("confidence", "")
                desc = cond.get("description", "")

                if y < 1.3 * inch:
                    c.showPage()
                    y = height - 0.75 * inch
                    c.setFont("Helvetica", 10)

                c.setFont("Helvetica-Bold", 10)
                c.drawString(0.75 * inch, y, f"{name} ({confidence} confidence)")
                y -= 0.18 * inch
                c.setFont("Helvetica", 9)
                for line in _wrap_text(desc, max_chars=100):
                    if y < 1.3 * inch:
                        c.showPage()
                        y = height - 0.75 * inch
                        c.setFont("Helvetica", 9)
                    c.drawString(1.0 * inch, y, line)
                    y -= 0.15 * inch
                y -= 0.1 * inch

        # Recommendations
        recommendations = analysis_result.get("recommendations") or []
        if recommendations:
            y -= 0.2 * inch
            if y < 1.3 * inch:
                c.showPage()
                y = height - 0.75 * inch
            c.setFont("Helvetica-Bold", 12)
            c.drawString(0.75 * inch, y, "Recommendations")
            y -= 0.25 * inch

            c.setFont("Helvetica", 10)
            for rec in recommendations:
                for line in _wrap_text(f"• {rec}", max_chars=95):
                    if y < 1.3 * inch:
                        c.showPage()
                        y = height - 0.75 * inch
                        c.setFont("Helvetica", 10)
                    c.drawString(0.75 * inch, y, line)
                    y -= 0.17 * inch

        # Disclaimer
        if y < 1.3 * inch:
            c.showPage()
            y = height - 0.75 * inch
        y -= 0.35 * inch
        c.setFont("Helvetica-Oblique", 8)
        disclaimer = analysis_result.get("disclaimer") or MEDICAL_DISCLAIMER
        for line in _wrap_text(disclaimer, max_chars=120):
            c.drawString(0.75 * inch, y, line)
            y -= 0.12 * inch

        c.showPage()
        c.save()
        buf.seek(0)
        return buf.read()


def _wrap_text(text: str, *, max_chars: int) -> list[str]:
    words = (text or "").split()
    lines: list[str] = []
    cur: list[str] = []
    cur_len = 0
    for w in words:
        add = len(w) + (1 if cur else 0)
        if cur_len + add > max_chars:
            lines.append(" ".join(cur))
            cur = [w]
            cur_len = len(w)
        else:
            cur.append(w)
            cur_len += add
    if cur:
        lines.append(" ".join(cur))
    return lines or [""]
